### ISSUE TITLE
[bug] can't use this plugin

### ISSUE THREAD

**Issue by bgchoi1118** [LinsMinecraftStudio/LighterAPI#1]
When I use this plugin and restart my server, it doesn't work with this log.
log:
`[21:17:56 INFO]: <LightAPI>: [INFO] Initializing LightAPI...
[21:17:56 INFO]: <LightAPI>: [INFO] Force legacy is enabled
[21:17:56 ERROR]: Error occurred while enabling LightAPI vbukkit-5.4.0-SNAPSHOT (build SNAPSHOT) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/lighting/LayerLightEngine
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.HandlerFactory.createHandler(HandlerFactory.java:71) ~[LightAPI-Bukkit-5.4.0-SNAPSHOT.jar:?]
        at ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initHandler(BukkitPlatformImpl.java:196) ~[LightAPI-Bukkit-5.4.0-SNAPSHOT.jar:?]
        at ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:228) ~[LightAPI-Bukkit-5.4.0-SNAPSHOT.jar:?]
        at ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88) ~[LightAPI-Bukkit-5.4.0-SNAPSHOT.jar:?]
        at ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70) ~[LightAPI-Bukkit-5.4.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reload(CraftServer.java:1039) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.Bukkit.reload(Bukkit.java:952) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:892) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.lighting.LayerLightEngine
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 25 more
[21:17:56 INFO]: [LightAPI] Disabling LightAPI vbukkit-5.4.0-SNAPSHOT (build SNAPSHOT)
[21:17:56 INFO]: <LightAPI>: [INFO] Shutdown LightAPI...`

**Comment by lijinhong11** [comment]
hmm, i will check that tomorrow

**Comment by lijinhong11** [comment]
You are using old version and we have fixed them in rc1(May contains bugs too)
