### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by OpticFusion1** [LinsMinecraftStudio/LighterAPI#2]
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_20_R3.VanillaNMSHandler.onBlockEmissionIncrease(VanillaNMSHandler.java:253) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_20_R3.VanillaNMSHandler.lambda$setRawLightLevel$0(VanillaNMSHandler.java:221) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_20_R3.VanillaNMSHandler.executeSync(VanillaNMSHandler.java:112) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_20_R3.VanillaNMSHandler.setRawLightLevel(VanillaNMSHandler.java:213) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.engine.sched.BukkitScheduledLightEngineImpl.setRawLightLevelLocked(BukkitScheduledLightEngineImpl.java:191) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.engine.sched.BukkitScheduledLightEngineImpl.setRawLightLevel(BukkitScheduledLightEngineImpl.java:197) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.common.internal.engine.sched.PriorityScheduler.handleLightRequest(PriorityScheduler.java:140) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.common.internal.engine.sched.ScheduledLightEngineImpl.handleLightRequest(ScheduledLightEngineImpl.java:261) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.common.internal.engine.sched.ScheduledLightEngineImpl.onShutdown(ScheduledLightEngineImpl.java:92) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.engine.sched.BukkitScheduledLightEngineImpl.onShutdown(BukkitScheduledLightEngineImpl.java:151) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.shutdown(BukkitPlatformImpl.java:246) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.common.LightAPI.shutdown(LightAPI.java:110) ~[?:?]
	at ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:268) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:475) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4045-Spigot-c198da2-38fd4bd]
	at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:895) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4045-Spigot-c198da2-38fd4bd]
	at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:697) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4045-Spigot-c198da2-38fd4bd]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1087) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4045-Spigot-c198da2-38fd4bd]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4045-Spigot-c198da2-38fd4bd]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by OpticFusion1** [comment]
Looks like the problem's fixed, however, lighting still doesn't work.
The impl I'm using atm is https://paste.md-5.net/kositaziku.java which is called via `getLightAPI().setLight(locs[locIndex], LightFlag.BLOCK_LIGHTING, 15, true, false);`

The setLightLevel num is `1`, likely important

**Comment by lijinhong11** [comment]
that's strange, yeah I use a new TickingTracker to do the job, so it may not work
I will check if I have time

**Comment by OpticFusion1** [comment]
That's the only class you'll have to test with, so you _should_ be fine to test and rewrite just that to work

**Comment by OpticFusion1** [comment]
Any updates?

**Comment by lijinhong11** [comment]
no bc i only have time on the weekends

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
